### ISSUE TITLE
When using fastify-bearer-auth in fastify-auth, there are error log when authenticate with other method

### ISSUE THREAD

**Issue by songpr** [fastify/fastify-bearer-auth#111]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.1

### Plugin version

6.0.0

### Node.js version

14.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 20.04

### Description

When using fastify-bearer-auth in fastify-auth, there are error log when authenticate with other method

like this 
`
{"level":50,"time":1637900599690,"pid":1354,"hostname":"SONG-WT-DELL","reqId":"req-2","msg":"invalid authorization header: `Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJsaW5lX3VzZXJfaWQiOiJVMzZkNDBjZjI0MWZjZWU4ZDZlNTY2YWI5NzFjMzgxYjYiLCJsaW5lX2lkX3Rva2VuX2lzc3VlX2F0IjoxNjM3OTAwNTk1MDU0LCJsaW5lX2lkX3Rva2VuX2V4cGlyZV9hdCI6MTYzNzkwNDE5NTA1NCwicmVmIjoiZTFiYmMyNzc1NjQwOTE1M2UyYzkxMzhhMGFhMTQ4MDAiLCJpYXQiOjE2Mzc5MDA1OTUsImV4cCI6MTYzNzkwNzc5NSwiaXNzIjoiYXBpLnN1cnZleS5hbXBtLnRsZCJ9.AEysztjEepz52HB4sMBh-6C-V_EqDz5quY5t7d_uPHpto8R7r06JnUK0eiuDMvbr6VTaTrsUyRIouAZ6U70h5FrZAJD1uWRZnYZ6QhaZWxbYA4L1pPRu-8wuzvvCBgzcG7pORcJX_3HK70FH5nMb02Ya4Wsr4rMhXPwlq9Mhn2yrP17j`"}
`

### Steps to Reproduce

- Just add fastify bearer as part of fastify-authen
- make sure it authenticate with other method e.g. jwt
- authenticate success but there is error log by fastify bearer

### Expected Behavior

If it is not the last authen method it must not log error - cause performance issues if there are a lot of valid requests.

**Comment by Eomm** [comment]
Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

Without it, we are unable to help you.

**Comment by songpr** [comment]
Here is how to reproduce,

1. start server with with fastify-auth and fastify-bearer-auth is the first authentication method

`
const fastify = require('fastify')({
  logger: {
    level: 'error'
  }
})
const auth = require('fastify-auth')
const bearerAuthPlugin = require('fastify-bearer-auth')
const keys = new Set(['a-super-secret-key', 'another-super-secret-key'])

async function server() {

  await fastify
    .register(auth)
    .register(bearerAuthPlugin, { addHook: false, keys })
    .decorate('allowAnonymous', function (req, reply, done) {
      if (req.headers.authorization) {
        return done(Error('not anonymous'))
      }
      return done()
    })

  fastify.route({
    method: 'GET',
    url: '/multiauth',
    preHandler: fastify.auth([
      fastify.verifyBearerAuth,
      fastify.allowAnonymous

    ]),
    handler: function (_, reply) {
      reply.send({ hello: 'world' })
    }
  })

  await fastify.listen({ port: 8000 });
  console.log("start hello successfully")
}

server()
`

2. call it with curl and it will get the proper answer
`curl http://localhost:8000/multiauth`

3.  However on the server log will have error log as shown below
> start hello successfully
{"level":50,"time":1642561062513,"pid":1170,"hostname":"SONG-WT-DELL","reqId":"req-1","msg":"unauthorized: missing authorization header"}
{"level":50,"time":1642561484218,"pid":1170,"hostname":"SONG-WT-DELL","reqId":"req-2","msg":"unauthorized: missing authorization header"}

4. Expected result is it call successfully but no error log since it will have impact to performance in case there are many requests.
5. My suggest solution, check addHook before log error
`    // retVal contains the result of the auth function if defined or the
    // result of the key comparison.
    // retVal is enclosed in a Promise.resolve to allow auth to be a normal
    // function or an async funtion. If it returns a non-promise value it
    // will be converted to a resolving promise. If it returns a promise it
    // will be resolved.
    Promise.resolve(retVal).then((val) => {
      // if val is not truthy return 401
      if (val === false) {
        if (addHook) request.log.error('unauthorized: %s', invalidKeyError.message)
        if (contentType) reply.header('content-type', contentType)
        reply.code(401)
        if (!addHook) return done(invalidKeyError)
        reply.send(errorResponse(invalidKeyError))
        return
      }`

**Comment by climba03003** [comment]
I would just add an option to disable the `logging` feature. 
The log is important to let the client know it is something wrong from the request.

**Comment by songpr** [comment]
> I would just add an option to disable the `logging` feature. The log is important to let the client know it is something wrong from the request.

In the multiple authentications case, they can access  successfully and it's not error, at most it's just warning.
It should not shown as error, as it's mislead.

**Comment by songpr** [comment]
> Could you add a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?
> 
> Without it, we are unable to help you.

I've provided example and solution. Could you please review and fix it?

**Comment by Fdawgs** [comment]
Closed by #120
