### ISSUE TITLE
Make token display in 'invalid authorization header' error controllable

### ISSUE THREAD

**Issue by FedericoMassaioli** [fastify/fastify-bearer-auth#118]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Presently, in case of an 'invalid authorization header', the invalid auth token is displayed in the error log, incurring the risk of revealing the majority of a mistyped or truncated and otherwise valid token, whose validity could last enough for a brute force attempt to reconstruct the missing part.

It would be better to implement one or more measures:

- move the token display to debug or trace log level, to at least avoid the risk in production environments
- remove altogether the token display in Node production mode
- add a specific configuration option with prudent defaults

or combinations thereof. 

### Motivation

Raise the security of services using the plugin.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by FedericoMassaioli** [comment]
I'd be glad to do it, but I'd agree on the preferred approach first.

**Comment by jsumners** [comment]
Just remove https://github.com/fastify/fastify-bearer-auth/blob/6e6ee1ecfaebbaf08653e4fb8ff8348bd5dc3c82/plugin.js#L62

**Comment by FedericoMassaioli** [comment]
@jsumners: done.
No additional unit tests seemed necessary, the case is already covered by existing tests, I was unable to find tests for log outputs.
