### ISSUE TITLE
Scoped paths

### ISSUE THREAD

**Issue by josmas** [fastify/fastify-bearer-auth#13]
Hi there, the readme states that one can register the plugin with [scopes](https://github.com/fastify/fastify/blob/master/docs/Routes.md#route-prefixing), but it seems to be using [fastify-plugin](https://github.com/fastify/fastify-plugin) for which scopes are not available. Can anyone clarify if it is possible? I've tried a few different things for prefixing but I either get a 404 or and invalid header. Many thanks!

**Comment by mcollina** [comment]
Would you mind make an example of what you are trying to achieve?

**Comment by josmas** [comment]
Hi @mcollina,

I basically want one route (at least one) that does not need a bearer token, so that I can issue one back to the client.

Using [route prefixing](https://github.com/fastify/fastify/blob/master/docs/Routes.md#route-prefixing) as explained in the docs, I could have say `/gettoken` without needing to send a token with the request, and then something like everything that is in `/v1/` needing the token or being rejected otherwise. Is that what the docs say for cases like `{ prefix: '/v1' }` or am I reading it wrong?

**Comment by mcollina** [comment]
That should work. Didn’t it? Can you make an example if not?

**Comment by josmas** [comment]
I might be doing something wrong, but I've tried passing _prefix_ in a few different places and not really getting anything. See the following:

```

fastify.register(bearerAuthPlugin, { prefix: '/v1', keys: keys  })

fastify.get('/', async (request, reply) => {
  return { hello: 'world' }
})

fastify.get('/v1/foo', async (request, reply) => {
  return { hello: 'foo' }
})

```

I would expect to be able to hit `curl localhost:3000` with no bearer, and have to pass a bearer for `curl localhost:3000/v1/foo -H "Authorization: Bearer secret"`. But both work with bearer, and won't authorise without it.

The docs specify that if using _fastify-plugin_, which this module uses, then prefixing will [not work](https://www.fastify.io/docs/latest/Plugins/#route-prefixing-option). But the readme for this plugin says the opposite.

**Comment by jsumners** [comment]
No, the readme says it supports "scoped paths":

```js
fastify.register((instance, opts, next) => {
  fastify.register(bearerAuthPlugin, {keys})
  fastify.get('/foo', (req, res) => res.send({hello: 'foo'}))
}, { prefix: '/v1' })

fastify.get('/', (req, res) => res.send({hello: 'world'}))
```

**Comment by jsumners** [comment]
Yes. Updated.

**Comment by josmas** [comment]
oh, I see, the route has to be registered on `instance`, now that makes sense. Thanks for the update, I can see how it works now.
