### ISSUE TITLE
Do not return error thrown in custom auth function to client

### ISSUE THREAD

**Issue by Immortalin** [fastify/fastify-bearer-auth#151]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10

### Plugin version

9.0

### Node.js version

19

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Jammy 22

### Description

If an error is thrown within the auth function, it is returned to the client. This default behaviour could potentially create vulnerable endpoints. E.g.

```Typescript
server.register(bearerAuthPlugin, {
  keys: new Set<string>(),
  auth(reqtoken, req) {
      return crypto.timingSafeEqual(Buffer.from("foo"), Buffer.from("barbazquux"))
  },
})
```

When `crypto.timingSafeEqual` throws an exception, the client gets the following mesage: `'{"error":"Input buffers must have the same byte length"}'`. This would allow them to infer the length of the key, disclosing unnecessary information. Currently this can be prevented by wrapping the `timingSafeEqual` function in a `try...catch` and returning `false` upon an exception. When using a `try...catch`, the correct message is returned `'{"error":"invalid authorization header"}'`.

### Steps to Reproduce

See above.

### Expected Behavior

Any exception thrown within the auth code is considered falsey and the default authorization denied message should be returned.

**Comment by climba03003** [comment]
When you provide a custom authentication method, it is the developer responsibility properly handle the error.
A library should not over control the custom behavior.

**Comment by mcollina** [comment]
Users should customize the error handler.
