### ISSUE TITLE
Does BearerType need to be case sensitive ?

### ISSUE THREAD

**Issue by olivierchatry** [fastify/fastify-bearer-auth#169]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Since v9.2.0, `BearerType` is being checked in a case sensitive way. This had the repercussion of breaking some of the clients that consume my API ( and had to revert to a previous version ).

Does this check must be case sensitive ? Other library seems to do a case insensitive check like described in these issues : 

https://github.com/lexik/LexikJWTAuthenticationBundle/issues/411

or

https://github.com/golang/oauth2/issues/113

**Comment by Uzlopak** [comment]
I personally also think, that it should be case insensitive because alot of clients send also lowercased bearertype.

**Comment by jsumners** [comment]
I think the spec is clear. And the linked issues agree. In my opinion, we should strictly follow the spec. However, I will not block a PR that adds a `looseCheck` option that will enable case insensitive checking of `Bearer`.

**Comment by Uzlopak** [comment]
I would prefer calling it `caseSensitive`.

**Comment by jsumners** [comment]
That's not accurate. The feature would be loosening the requirement set forth by the spec.

**Comment by Uzlopak** [comment]
`caseSensitive` would be set to `true`  by default, according to the spec. If you want to deviate you would set `caseSensitive` to `false`

Actually should be `bearerTypeCaseSensitive`

`looseCheck`would be describing not precisely what it does.

**Comment by Uzlopak** [comment]
Provided PR #172
