### ISSUE TITLE
When using typescript with @fastify/auth, verifyBearerAuth throws a "Type 'verifyBearerAuth | undefined' is not assignable to type 'FastifyAuthFunction | FastifyAuthFunction[]'" 

### ISSUE THREAD

**Issue by brunoshine** [fastify/fastify-bearer-auth#176]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.25.2

### Plugin version

9.3.0

### Node.js version

20.9.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 22.04.2 LTS

### Description

Picking up on the sample provided on the REAME for the integration with `@fastify/auth`, if we create a route with just the `fastify.verifyBearerAuth` we get a typescript error `Type 'verifyBearerAuth | undefined' is not assignable to type 'FastifyAuthFunction | FastifyAuthFunction[]'.
  Type 'undefined' is not assignable to type 'FastifyAuthFunction | FastifyAuthFunction[]'.ts(2322)`
  
  ```js

    fastify.route({
        method: 'GET',
        url: '/bearer',
        preHandler: fastify.auth([fastify.verifyBearerAuth]),
        handler: function (_, reply) {
            reply.send({ hello: 'world' })
        }
    })
  ```

The workaround was to add a `// @ts-ignore`
```js
 fastify.route({
        method: 'GET',
        url: '/bearer',
        // @ts-ignore <<<<<<<<<<<<<<< workaround
        preHandler: fastify.auth([fastify.verifyBearerAuth]),
        handler: function (_, reply) {
            reply.send({ hello: 'world' })
        }
    })
```

Any thoughts? thanks

### Steps to Reproduce

Follow the README sample and add a route with just the verifybearerauth call:

```
    fastify.route({
        method: 'GET',
        url: '/bearer',
        preHandler: fastify.auth([fastify.verifyBearerAuth]),
        handler: function (_, reply) {
            reply.send({ hello: 'world' })
        }
    })
```

### Expected Behavior

Should work without the error.

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests (we use tsd for typescript)

**Comment by casantosmu** [comment]
`verifyBearerAuth` is declared as undefined [here](https://github.com/fastify/fastify-bearer-auth/blob/ba2792a79e3b3843b71c87410e2dde5786fcafad/types/index.d.ts#L10). This reflects the reality that Fastify cannot automatically determine the presence of specific decorators in each context.

To address this, you can manually check for `verifyBearerAuth` before defining the route:

```javascript
if (!fastify.verifyBearerAuth) {
  throw new Error("Fastify verifyBearerAuth decorator required");
}

fastify.route({
  method: "GET",
  url: "/bearer",
  preHandler: fastify.auth([fastify.verifyBearerAuth]),
  handler: function (_, reply) {
    reply.send({ hello: "world" });
  },
});
```

However, many plugins in the Fastify ecosystem declare these decorators as defined. I could update the module declaration to remove the possibility of `verifyBearerAuth` being undefined, changing this:

```typescript
declare module 'fastify' {
  interface FastifyInstance {
    verifyBearerAuthFactory?: fastifyBearerAuth.verifyBearerAuthFactory
    verifyBearerAuth?: fastifyBearerAuth.verifyBearerAuth
  }
}
```

To this:

```typescript
declare module 'fastify' {
  interface FastifyInstance {
    verifyBearerAuthFactory: fastifyBearerAuth.verifyBearerAuthFactory
    verifyBearerAuth: fastifyBearerAuth.verifyBearerAuth
  }
}
```

@mcollina what do you think?

**Comment by mcollina** [comment]
I would do that.

**Comment by climba03003** [comment]
It is marked as `undefined` because those methods is not added by default.
I believe extra checking on the existence is a good idea.

If it removes the `?` part, I believe there would be a bug report telling why those methods is `undefined`.

**Comment by casantosmu** [comment]
I believe it is preferable to catch errors during the build process rather than encountering them at runtime.

**Comment by climba03003** [comment]
If you compare with other plugins, they exist in non-nullable methods only because they are always defined.

I don't think the current types is wrong, change it is giving a false image to the users it is always defined.

I don't want to be chasing it back and forth.

**Comment by Fdawgs** [comment]
I think @casantosmu's solution is best for this, closing.
