### ISSUE TITLE
Authenticates without a valid key, 1 char key while 512 char key is required 

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [fastify/fastify-bearer-auth#190]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.28.1

### Plugin version

9.4.0

### Node.js version

22.8.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu Server

### Description

I want to secure my API using bearer keys.
I have created a 512digit key and added it to the keys array.

In my understanding is that the bearer auth should only allow access to people who have a 100% matching key.

Meanwhile I can type my api URL and add "t" as a key and it authenticates me and gives me full access.

Is the key too long? I don't have a login but just a bearer key.

### Expected Behavior

Not authenticating me with a 1 digit while the key is 512 chars long.

**Comment by Uzlopak** [comment]
Can you provide a mvce?

**Comment by 4e576rt8uh9ij9okp** [comment]
> Can you provide a mvce?

I will try, can be that it's my fault.
I'm currently at work you can maybe have a look here.

https://codeberg.org/fossapp-com/musicplayer

**Comment by 4e576rt8uh9ij9okp** [comment]
> Can you provide a mvce?

Excuse me for causing trouble, I have tried to replicate it and the issue was that I had `addHook: false` inside the options.
