### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-bearer-auth#2]
I recommend providing a validation function instead of a set of keys.

**Comment by jsumners** [comment]
What are you talking about? Of course the header is validated.

**Comment by StarpTech** [comment]
As a user, I expect that my header **and token** is **validated** but the purpose of this package is to check that the header exists otherwise we return `Unauthorized`.

E.g in https://github.com/johnbrett/hapi-auth-bearer-token they provide a way to validate the token. This is needed to categorize this module in `auth` otherwise it's a simple header check.

```js
    server.auth.strategy('simple', 'bearer-access-token', {
        allowQueryToken: true,              // optional, false by default
        validate: async (request, token, h) => {

            // here is where you validate your token
            // comparing with token from your database for example
            const isValid = token === '1234';

            const credentials = { token };
            const artifacts = { test: 'info' };

            return { isValid, credentials, artifacts };
        }
    });
```

**Comment by jsumners** [comment]
Again, I don't know what you're talking about. The key in the header is validated at https://github.com/fastify/fastify-bearer-auth/blob/5f39632c3eec6119b6eab00c251a42f3088330e7/plugin.js#L28

**Comment by StarpTech** [comment]
Forget it, I didn't find it, my fault. But my recommendation is to provide a validation function instead of a set of keys.

```js
validate: async (request, token, h) => {

            // here is where you validate your token
            // comparing with token from your database for example
            const isValid = token === '1234';

            const credentials = { token };
            const artifacts = { test: 'info' };

            return { isValid, credentials, artifacts };
        }
```

**Comment by jsumners** [comment]
Why? What is the advantage over using a key set? Also, the requirement is only that it _look_ like a key set. As long as the `has` method is synchronous it does not matter.

**Comment by StarpTech** [comment]
Because we don't have access to the `request` object. We can't react to specific request conditions. The set of keys must be fixed at `.register` we can't implement a lookup in an external storage.

**Comment by StarpTech** [comment]
It's not uncommon to validate the token against a service.

**Comment by jsumners** [comment]
I don't see a PR implementing what you want.

**Comment by jsumners** [comment]
I'm working on this and I'm not sure about handling errors in the `async` hook. Normally, returning `undefined` is going to stop the request. But in an `async` hook I'm pretty sure I need to return/throw and `Error` to stop the request. But I will have already sent the error response due to the features of the plugin and Fastify is then going to try and send the returned/thrown error.

**Comment by StarpTech** [comment]
Add the validation function as a separate hook.

```js
function plugin (fastify, options, next) {
  const hook = internals.factory(options)
  fastify.addHook('preHandler', hook)
  fastify.addHook('preHandler', opts.validation)
  next()
}
```

**Comment by jsumners** [comment]
That's not what I'm saying. I'll have to work up a simple test case when I have more time.

**Comment by StarpTech** [comment]
If you handle it as a preHandler hook function you don't have to care about error handling. It's up to the developer.

**Comment by wilg** [comment]
I'm confused by this. Does this package not support validating the bearer token with an external service (like a database)? It seems like it doesn't, which is very surprising.

**Comment by mcollina** [comment]
Would you like to open a PR?

**Comment by wilg** [comment]
Not sure, I guess that depends on the answer to my question!

**Comment by mcollina** [comment]
Looking at the code it doesnt. Even if it does, adding some tests for it would be awesome
