### ISSUE TITLE
How to enable bearer-auth for specific routes

### ISSUE THREAD

**Issue by carlosfaria94** [fastify/fastify-bearer-auth#27]
Hi,

I already have drop this question two times on Gitter, but no answers.

I want to know how can I enable this plugin to specific routes?

E.g. Require the bearer token on `/sensitive` but not in `/login`

The README states that it is possible, but I didn't found any guidance here or in fastify docs.

Thanks

**Comment by Eomm** [comment]
You need to use the fastify encapsulation splitting the scope where you register the plugin:

```js
fastify.register((instance, opts, next)=>{
  instance.register(bearerAuthPlugin, {keys})
  instance.get('/sensitive', (req, res)=>{res.send('hello')})
})
fastify.register((instance, opts, next)=>{
  instance.get('/login', (req, res)=>{res.send('hello')})
})
```

**Comment by carlosfaria94** [comment]
Thank you @Eomm
