### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by ricardo-devis-agullo** [fastify/fastify-bearer-auth#28]
## 🚀 Feature Proposal

Add an index.d.ts with Typescript type definitions.

## Motivation

To use it on Typescript projects.

I can do a PR for this if you are ok with it.

**Comment by SerayaEryn** [comment]
Please feel free to open a PR.

**Comment by ricardo-devis-agullo** [comment]
Done! :)

**Comment by FreeleX** [comment]
Can this issue be closed? :)

**Comment by mcollina** [comment]
Yes!
