### ISSUE TITLE
Remove `request` dependency

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-bearer-auth#32]
The `request` module has been deprecated for a long time. We need to remove it as a dependency from this module. This can be accomplished by using [`got](https://npm.im/got) or, ideally, using Fastify's [built-in request injection](https://www.fastify.io/docs/latest/Testing/).

**Comment by agarwalkartik** [comment]
Hey, I would like to handle this issue. Is it still open to take up ?

**Comment by mcollina** [comment]
sure, go ahead!
Il 3 mar 2020, 20:19 +0100, Kartik Agarwal <notifications@github.com>, ha scritto:

**Comment by Eomm** [comment]
Closed in #36
