### ISSUE TITLE
Remove unsupported Node.js versions

### ISSUE THREAD

**Issue by jsumners** [fastify/fastify-bearer-auth#34]
We need to stop testing against EOL versions of Node.js and start testing against all current versions.

**Comment by agarwalkartik** [comment]
I see that currently ``` [ '10', '8', '6' ]``` these versions are tested. It should be pretty straight forward to change the versions to newer ones (in the workflows file). I guess testing against 10,12 and 13 should be good enough?

**Comment by Eomm** [comment]
Not so easy 😄 

The checks todo are:

- [ ] update the dependencies with the major versions
- [ ] update the source code if necessary due the dependancies
- [ ] clean the greenkeeper ignore in `package.json`
- [ ] update the source code if necessary (for example the spread operator doesn't work in node 6.. now we can use it!)
- [ ] update the ci workflow

**Comment by agarwalkartik** [comment]
Oh, I underestimated it, but would be happy to start with it anyway.

**Comment by Eomm** [comment]
It was good!

> do you think any update in the codebase is required?

In this case I think it is not 👍 

Thanks!


Closed in #37

**Comment by agarwalkartik** [comment]
Cool, thanks a lot!!
