### ISSUE TITLE
Cannot use plugin per path only

### ISSUE THREAD

**Issue by FreeleX** [fastify/fastify-bearer-auth#46]
## 🐛 Bug Report

Per plugin documentation:
```
fastify-bearer-auth exports a standard Fastify plugin. 
This allows you to register the plugin within scoped paths. 
Therefore, you could have some paths that are not protected by the plugin and others that are. 
See the Fastify documentation and examples for more details.
```

But in https://www.fastify.io/docs/latest/Plugins/ 
```
The currently supported list of Fastify specific options is:

logLevel
logSerializers
prefix

Note: Those options will be ignored when used with fastify-plugin
```

And basically seems like because under the hood `fastify-bearer-auth` is wrapped into `fastify-plugin` call this way does not work (all the routes are behind auth check instead of just one route)

What works is using `bearerAuthPlugin.internals.factory` with `onRequest` fastify hook for the route, but obviously it is just a workaround

## To Reproduce

Example of code tried:

```js
import authPlugin from 'fastify-bearer-auth'

const keys = new Set(['testme'])

fastifyInstance.register(authPlugin, {
   prefix: '/protected-test-route',
   keys,
   errorResponse: () => {
       return { error: 'Unauthorized error' }
   },
})
```

## Expected behavior

200 OK when trying to access / route

## Actual behaviour

401 Unauthorized when trying to access / route

## Your Environment

- *node version*: 12.18.2
- *fastify version*: 3.0.0
- *os*: Mac
- *language*: typescript

**Comment by jsumners** [comment]
See https://github.com/fastify/help/issues/174

**Comment by FreeleX** [comment]
@jsumners Thx, but I found that for my project it could be more useful to have the ability to use factory directly as kind of connect-style middleware. Would it be OK if I contribute PR where we export factory directly also (not as an internal property and together with TS types too)? 

This also allows me to use it in different hooks e.g. preHandler, onRequest. BTW I see in source code that plugin registers via onRequest hook while in README it says `Internally, the plugin registers a standard Fastify preHandler hook`

**Comment by jsumners** [comment]
> kind of connect-style middleware

I don't know what that means.

We use `fastify-plugin` to guarantee that the plugin is loaded into a supported Fastify environment and to work in an expected fashion. To scope the plugin to a specific set of routes:

```js
fastifyInstance.register(async i => {
  i.register(authPlugin, {
    prefix: '/protected-test-route',
    keys,
    errorResponse () {
      return { error: 'Unauthorized error' }
    }
  })
})
```

A PR to add this to the docs, and to correct the note about which lifecycle hook the plugin uses, would be welcome.

**Comment by FreeleX** [comment]
By connect-style middleware I meant as a function which expects `(request, response, next)`, the same signature as `function bearerAuthHook (fastifyReq, fastifyRes, next) {` already has

What if I need it for several routes not sharing common prefix? 
E.g. `/some-protected-test-route1, /another-protected-test-route2, /yet-another-protected-test-rout3` ? 
Do I need to register plugin several times?

**Comment by jsumners** [comment]
Yes, you should register the plugin multiple times for each separate scope you want it to apply to.

`function bearerAuthHook (fastifyReq, fastifyRes, next) {}` is the signature for a Fastify style plugin. See https://www.fastify.io/docs/v3.2.x/Plugins/.

**Comment by FreeleX** [comment]
Unfortunately, the register code above does not work (auth becomes disabled for all routes).
Also I tried to understand why and came up with the following snippet:
```
    fastifyInstance.addHook('onRequest', (_req, _res, next) => {
      console.log('onRequest1')
      next()
    })

    fastifyInstance.register(async (i) => {
      i.addHook('onRequest', (_req, _res, next) => {
        console.log('onRequest2')
        next()
      })
    })
```
onRequest1 gets printed, but onRequest2 does not.

Also, this way of multiple registerings complicates things and honestly confuses me.

Would be better to have the possibility to use package as route option also https://www.fastify.io/docs/master/Routes/#routes-option which means just exporting existing `factory` function which returns `function bearerAuthHook (fastifyReq, fastifyRes, next) {` could be enough. 
Should we just do it? :)

**Comment by Eomm** [comment]
>Also, this way of multiple registerings complicates things and honestly confuses me.

This is the better feature of fastify: encapsulated context:
```
    fastifyInstance.register(async (i) => {
      i.addHook('onRequest', (_req, _res, next) => {
        console.log('onRequest2')
        next()
      })
      
      i.get('/hello', async ()=> 'hi')
    })
```

If you call `/hello` the `onRequest2` will be executed

Every `register` is like an independent isle where you can do what you want without breaking other isles. [here](https://stackoverflow.com/a/61054534/3309466) a TL;DR answer

**Comment by FreeleX** [comment]
Thx for the explanation, I've got it, but, sorry for repeating this again, extra flexibility - the possibility to use package as route option also fastify.io/docs/master/Routes/#routes-option would be much appreciated if it does not impact anything

**Comment by FreeleX** [comment]
I can contribute the docs fix and/or the possibility to use the package at a route level if you support, but I have found another way to solve my bearer auth middleware task as the suggested approach with `fastifyInstance.register` is unnecessarily complicated for me and coupled to fatisfy register specifics (I understand that this package is called fastify-bearer-auth, so no blame). 
Still, I developed my part of the code in a more framework-agnostic way, so while integration with this package at a route level could be an option, the register way just did not fit.
Otherwise, feel free to close the issue (or tell me to close), thank you so much for providing more info and answering my questions :)

**Comment by jsumners** [comment]
I really don't know how to support "this is a Fastify plugin but I don't want to use Fastify."
