### ISSUE TITLE
Allow Anonymous Access

### ISSUE THREAD

**Issue by cliedeman** [fastify/fastify-bearer-auth#63]
## 🚀 Feature Proposal

Allow anonymous access

## Motivation

Make the authorization header optional via config
I took a look at fastify-auth and plugin scopes but cannot see a way to achive this

## Example

```js
'use strict'

const fastify = require('fastify')()
const bearerAuthPlugin = require('fastify-bearer-auth')
const keys = new Set(['a-super-secret-key', 'another-super-secret-key'])

fastify.register(bearerAuthPlugin, {keys, allowAnonymous: true})

fastify.get('/foo', (req, reply) => {
  reply.send("Public Endpoint")
})

fastify.listen({port: 8000}, (err) => {
  if (err) {
    fastify.log.error(err.message)
    process.exit(1)
  }
  fastify.log.info('http://127.0.0.1:8000/foo')
})
```

Example Changes 
```js
if (!header) {
     if (allowAnonymous) {
          return next();
     }
      const noHeaderError = Error('missing authorization header')
      fastifyReq.log.error('unauthorized: %s', noHeaderError.message)
      if (contentType) fastifyRes.header('content-type', contentType)
      fastifyRes.code(401).send(errorResponse(noHeaderError))
      return
    }
```

**Comment by mcollina** [comment]
We should also support something like:

```js
fastify.get('/foo', { config: { allowAnonymous: true } }, (req, reply) => {
  reply.send("Public Endpoint")
})
```

or

```js
fastify.get('/foo', { allowAnonymous: true }, (req, reply) => {
  reply.send("Public Endpoint")
})
```

You can access that info inside `req.context`

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by cliedeman** [comment]
@mcollina I have sent a pull request for the first part.

For the second part. Can't that be solved with scoped registrations?

**Comment by jsumners** [comment]
I don't understand the original ask. How is this not provided by https://github.com/fastify/fastify/blob/fc33ae97ed2de9d2c9c262f5efb966c84e942547/docs/Encapsulation.md?

**Comment by cliedeman** [comment]
@jsumners its a single graphql endpoint.

Its only one route that I want to allow anonymous and authenticated access

**Comment by jsumners** [comment]
How can one endpoint support authenticated and unauthenticated requests at the same time via a simple bearer token?

**Comment by mcollina** [comment]
> How can one endpoint support authenticated and unauthenticated requests at the same time via a simple bearer token?

Unfortunately this is more common that what'd think. As an example github APIs supports both authenticated and unauthenticated access... they issue a different rate limit for the user.

**Comment by jsumners** [comment]
🤔 that's a case I hadn't considered.

**Comment by climba03003** [comment]
Why dont you combine this plugin with [`fastify-auth`](https://github.com/fastify/fastify-auth) ?
You can do something like,

```JS
fastify.route(
  method: 'GET',
  url: '/',
  preHandler: fastify,auth([
    fastify.allowAnonymous,
    fastify.allowBeraerAuth
  ]),
  handler: (req, reply) => {
    req.log.info('Auth route')
    reply.send({ hello: 'world' })
  }
)
```

**Comment by cliedeman** [comment]
Hi @climba03003 

I tried that first but couldn't figure out how to integrate the two.

I created a example repo [here](https://github.com/cliedeman/fastify-anonymous-example/blob/master/src/app.ts#L40)

**Comment by climba03003** [comment]
This need a PR, as `fastify-bearer-auth` do not expose the `authentication` method for you to use it and it register the `preHandler` for all routes.

Works need to be done.
1. The register for routes should be optional.
2. Expose the `authentication` through `decorater`
