### ISSUE TITLE
Vulnerable to timing attacks?

### ISSUE THREAD

**Issue by StarpTech** [fastify/fastify-bearer-auth#7]
Code: https://github.com/fastify/fastify-bearer-auth/blob/master/plugin.js#L28
Vulnerability: https://snyk.io/blog/node-js-timing-attack-ccc-ctf/

Use: https://github.com/vadimdemedes/secure-compare

**Comment by jsumners** [comment]
This would have been better to report in private channels. However, can you find any information that `Set.prototype.has` is susceptible?

**Comment by StarpTech** [comment]
Yes, [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Value_equality).

**Comment by jsumners** [comment]
Are those links about the V8 implementation?

**Comment by StarpTech** [comment]
No about ECMAScript 6

**Comment by jsumners** [comment]
I agree that you are likely correct. However, the specification does not correlate to the implementation. And there two parts to this:

1. The algorithm behind `.has` and how it determines `true` or `false`.
2. The complexity of the keys within the set. Weak keys will always mean weak security.

Regardless, if you have a PR to solve the _potential_ issue, feel free to submit it.

**Comment by StarpTech** [comment]
Done https://github.com/fastify/fastify-bearer-auth/pull/8
