### ISSUE TITLE
When used with fastify-auth, if the bearer auth fails, no subsequent fastify-auth options execute

### ISSUE THREAD

**Issue by ahgentil** [fastify/fastify-bearer-auth#90]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3

### Plugin version

5.1.0

### Node.js version

14

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.2.3

### Description

When `fastify-bearer-auth` is registered with `{ addHook: false }`, so it can be used with `fastify-auth`, `fastify.verifyBearerAuth` needs to be the last element on `fastify.auth([])` or any other options after it will new be tested (because it responds immediately on failure - `reply.send()`).

Regarding errors it's also not ideal because, since it needs to be in the end of the lis, the errored response will always be from `fastify-bearer-auth`.

### Steps to Reproduce

Just add a preHandler hook similar to:

```
fastify.addHook('preHandler',
  fastify.auth([
    fastify.someAuth1, 
    fastify.verifyBearerAuth,
    fastify.someAuth2 // this will never be tested/executed
  ])
)
```

### Expected Behavior

For `fastify.verifyBearerAuth` not to respond back and to throw an error, which would make `fastify-auth` test the next handler in the list.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
